site_name: olfactory_navigation_docs

theme:
  name: "material"
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

repo_url: https://github.com/PimLb/olfactory-navigation

nav:
  - Home: 'index.md'
  - Code Reference: reference/
