site_name: Olfactory Navigation Documentation

theme:
  name: "material"
  logo: "img/squid_drawing.png"
  favicon: "img/squid_drawing.png"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

repo_name: PimLb/olfactory-navigation
repo_url: https://github.com/PimLb/olfactory-navigation

nav:
  - Home: 'index.md'
  - Code Reference: reference/
  - Tutorials:
    - 'What is an Environment?': 'tutorials/environment_description.md'
    - 'What is an Agent?': 'tutorials/agent_description.md'
    - 'How does a simulation work?': 'tutorials/simulation_process.md'
    - 'What tests are available?': 'tutorials/available_tests.md'
